name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node modules
        run: |
          npm install
          npm install -g @angular/cli

      - name: Build the project
        run: ng build
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::613111389734:role/GithubActions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      - name: Copy build to s3
        run: |
          aws s3 sync ./dist s3://magic-survival-tips/
      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id E1I7HHHRU5FUYJ --paths "/*"
